"""
Configuration module for Teiken Claw.

This module provides:
- Application settings (from environment variables)
- Logging configuration
- Application constants
"""

from app.config.settings import Settings, settings, get_settings
from app.config.logging import (
    setup_logging,
    get_logger,
    get_trace_id,
    set_trace_id,
    get_job_id,
    set_job_id,
    get_session_id,
    set_session_id,
    get_thread_id,
    set_thread_id,
    get_component,
    set_component,
    clear_context,
    StructuredLogger,
    StructuredFormatter,
    ConsoleFormatter,
)
from app.config.constants import (
    # Application
    APP_NAME,
    APP_DESCRIPTION,
    APP_VERSION,
    
    # Environment
    ENVIRONMENT_DEVELOPMENT,
    ENVIRONMENT_PRODUCTION,
    ENVIRONMENT_TESTING,
    
    # Job Priority
    JOB_PRIORITY_INTERACTIVE,
    JOB_PRIORITY_SUBAGENT,
    JOB_PRIORITY_SCHEDULED,
    JOB_PRIORITY_MAINTENANCE,
    
    # Control State
    CONTROL_KEY_MAINTENANCE_MODE,
    CONTROL_KEY_MAX_CONCURRENT_JOBS,
    CONTROL_KEY_MEMORY_ENABLED,
    CONTROL_KEY_SCHEDULER_ENABLED,
    CONTROL_KEY_LAST_MIGRATION_VERSION,
    CONTROL_KEY_FEATURE_FLAGS,
    DEFAULT_CONTROL_STATES,
    
    # Database
    DATABASE_SQLITE,
    DATABASE_POSTGRES,
    DATABASE_MYSQL,
    SQLITE_JOURNAL_MODE_WAL,
    SQLITE_SYNCHRONOUS_NORMAL,
    SQLITE_BUSY_TIMEOUT_MS,
    
    # Queue
    QUEUE_REDIS,
    QUEUE_SQLITE,
    QUEUE_RABBITMQ,
    QUEUE_SQS,
    QUEUE_STATUS_PENDING,
    QUEUE_STATUS_RUNNING,
    QUEUE_STATUS_COMPLETED,
    QUEUE_STATUS_FAILED,
    QUEUE_STATUS_CANCELLED,
    
    # Memory
    MEMORY_REDIS,
    MEMORY_SQLITE,
    MEMORY_MEMCACHED,
    MEMORY_IN_MEMORY,
    MEMORY_TYPE_EPISODIC,
    MEMORY_TYPE_SEMANTIC,
    MEMORY_TYPE_PROCEDURAL,
    MEMORY_TYPE_WORKING,
    MEMORY_SCOPE_GLOBAL,
    MEMORY_SCOPE_SESSION,
    MEMORY_SCOPE_USER,
    
    # Agent
    AGENT_STATUS_ACTIVE,
    AGENT_STATUS_INACTIVE,
    AGENT_STATUS_ERROR,
    ROLE_USER,
    ROLE_ASSISTANT,
    ROLE_SYSTEM,
    ROLE_TOOL,
    
    # Scheduler
    TRIGGER_TYPE_INTERVAL,
    TRIGGER_TYPE_CRON,
    TRIGGER_TYPE_DATE,
    TRIGGER_TYPE_ONCE,
    SCHEDULER_STATUS_PENDING,
    SCHEDULER_STATUS_RUNNING,
    SCHEDULER_STATUS_COMPLETED,
    SCHEDULER_STATUS_FAILED,
    SCHEDULER_STATUS_CANCELLED,
    
    # HTTP Status
    HTTP_STATUS_OK,
    HTTP_STATUS_CREATED,
    HTTP_STATUS_NO_CONTENT,
    HTTP_STATUS_BAD_REQUEST,
    HTTP_STATUS_UNAUTHORIZED,
    HTTP_STATUS_FORBIDDEN,
    HTTP_STATUS_NOT_FOUND,
    HTTP_STATUS_CONFLICT,
    HTTP_STATUS_UNPROCESSABLE_ENTITY,
    HTTP_STATUS_TOO_MANY_REQUESTS,
    HTTP_STATUS_INTERNAL_ERROR,
    HTTP_STATUS_NOT_IMPLEMENTED,
    HTTP_STATUS_SERVICE_UNAVAILABLE,
    
    # Time
    SECONDS_IN_MINUTE,
    SECONDS_IN_HOUR,
    SECONDS_IN_DAY,
    SECONDS_IN_WEEK,
    MS_IN_SECOND,
    MS_IN_MINUTE,
    MS_IN_HOUR,
    
    # Paths
    LOGS_DIR,
    CONFIG_DIR,
    DATA_DIR,
    TEMP_DIR,
    WORKSPACE_DIR,
    
    # Defaults
    DEFAULT_TIMEOUT,
    DEFAULT_PAGE_SIZE,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_DELAY,
    DEFAULT_MAX_CONCURRENT_JOBS,
    DEFAULT_OLLAMA_TIMEOUT,
    DEFAULT_OLLAMA_MAX_CONCURRENCY,
    DEFAULT_OLLAMA_CHAT_MODEL,
    DEFAULT_OLLAMA_EMBED_MODEL,
    DEFAULT_TELEGRAM_GLOBAL_MSG_PER_SEC,
    DEFAULT_TELEGRAM_PER_CHAT_MSG_PER_SEC,
    DEFAULT_MAX_TOOL_TURNS,
    DEFAULT_AGENT_TIMEOUT,
    
    # Feature Flags
    FEATURE_MEMORY_ENABLED,
    FEATURE_SCHEDULER_ENABLED,
    FEATURE_SUBAGENTS_ENABLED,
    FEATURE_WEB_SEARCH_ENABLED,
    FEATURE_CODE_EXECUTION_ENABLED,
    
    # Events
    EVENT_APP_STARTUP,
    EVENT_APP_SHUTDOWN,
    EVENT_REQUEST_START,
    EVENT_REQUEST_END,
    EVENT_JOB_START,
    EVENT_JOB_END,
    EVENT_JOB_ERROR,
    EVENT_MEMORY_CREATE,
    EVENT_MEMORY_UPDATE,
    EVENT_MEMORY_DELETE,
    EVENT_TOOL_CALL,
    EVENT_TOOL_ERROR,
    
    # Error Codes
    ERROR_CODE_UNKNOWN,
    ERROR_CODE_TIMEOUT,
    ERROR_CODE_RATE_LIMIT,
    ERROR_CODE_VALIDATION,
    ERROR_CODE_NOT_FOUND,
    ERROR_CODE_UNAUTHORIZED,
    ERROR_CODE_FORBIDDEN,
    ERROR_CODE_CONFLICT,
    ERROR_CODE_INTERNAL,
    ERROR_CODE_SERVICE_UNAVAILABLE,
)


__all__ = [
    # Settings
    "Settings",
    "settings",
    "get_settings",
    
    # Logging
    "setup_logging",
    "get_logger",
    "get_trace_id",
    "set_trace_id",
    "get_job_id",
    "set_job_id",
    "get_session_id",
    "set_session_id",
    "get_thread_id",
    "set_thread_id",
    "get_component",
    "set_component",
    "clear_context",
    "StructuredLogger",
    "StructuredFormatter",
    "ConsoleFormatter",
    
    # Constants - Application
    "APP_NAME",
    "APP_DESCRIPTION",
    "APP_VERSION",
    
    # Constants - Environment
    "ENVIRONMENT_DEVELOPMENT",
    "ENVIRONMENT_PRODUCTION",
    "ENVIRONMENT_TESTING",
    
    # Constants - Job Priority
    "JOB_PRIORITY_INTERACTIVE",
    "JOB_PRIORITY_SUBAGENT",
    "JOB_PRIORITY_SCHEDULED",
    "JOB_PRIORITY_MAINTENANCE",
    
    # Constants - Control State
    "CONTROL_KEY_MAINTENANCE_MODE",
    "CONTROL_KEY_MAX_CONCURRENT_JOBS",
    "CONTROL_KEY_MEMORY_ENABLED",
    "CONTROL_KEY_SCHEDULER_ENABLED",
    "CONTROL_KEY_LAST_MIGRATION_VERSION",
    "CONTROL_KEY_FEATURE_FLAGS",
    "DEFAULT_CONTROL_STATES",
    
    # Constants - Database
    "DATABASE_SQLITE",
    "DATABASE_POSTGRES",
    "DATABASE_MYSQL",
    "SQLITE_JOURNAL_MODE_WAL",
    "SQLITE_SYNCHRONOUS_NORMAL",
    "SQLITE_BUSY_TIMEOUT_MS",
    
    # Constants - Queue
    "QUEUE_REDIS",
    "QUEUE_SQLITE",
    "QUEUE_RABBITMQ",
    "QUEUE_SQS",
    "QUEUE_STATUS_PENDING",
    "QUEUE_STATUS_RUNNING",
    "QUEUE_STATUS_COMPLETED",
    "QUEUE_STATUS_FAILED",
    "QUEUE_STATUS_CANCELLED",
    
    # Constants - Memory
    "MEMORY_REDIS",
    "MEMORY_SQLITE",
    "MEMORY_MEMCACHED",
    "MEMORY_IN_MEMORY",
    "MEMORY_TYPE_EPISODIC",
    "MEMORY_TYPE_SEMANTIC",
    "MEMORY_TYPE_PROCEDURAL",
    "MEMORY_TYPE_WORKING",
    "MEMORY_SCOPE_GLOBAL",
    "MEMORY_SCOPE_SESSION",
    "MEMORY_SCOPE_USER",
    
    # Constants - Agent
    "AGENT_STATUS_ACTIVE",
    "AGENT_STATUS_INACTIVE",
    "AGENT_STATUS_ERROR",
    "ROLE_USER",
    "ROLE_ASSISTANT",
    "ROLE_SYSTEM",
    "ROLE_TOOL",
    
    # Constants - Scheduler
    "TRIGGER_TYPE_INTERVAL",
    "TRIGGER_TYPE_CRON",
    "TRIGGER_TYPE_DATE",
    "TRIGGER_TYPE_ONCE",
    "SCHEDULER_STATUS_PENDING",
    "SCHEDULER_STATUS_RUNNING",
    "SCHEDULER_STATUS_COMPLETED",
    "SCHEDULER_STATUS_FAILED",
    "SCHEDULER_STATUS_CANCELLED",
    
    # Constants - HTTP Status
    "HTTP_STATUS_OK",
    "HTTP_STATUS_CREATED",
    "HTTP_STATUS_NO_CONTENT",
    "HTTP_STATUS_BAD_REQUEST",
    "HTTP_STATUS_UNAUTHORIZED",
    "HTTP_STATUS_FORBIDDEN",
    "HTTP_STATUS_NOT_FOUND",
    "HTTP_STATUS_CONFLICT",
    "HTTP_STATUS_UNPROCESSABLE_ENTITY",
    "HTTP_STATUS_TOO_MANY_REQUESTS",
    "HTTP_STATUS_INTERNAL_ERROR",
    "HTTP_STATUS_NOT_IMPLEMENTED",
    "HTTP_STATUS_SERVICE_UNAVAILABLE",
    
    # Constants - Time
    "SECONDS_IN_MINUTE",
    "SECONDS_IN_HOUR",
    "SECONDS_IN_DAY",
    "SECONDS_IN_WEEK",
    "MS_IN_SECOND",
    "MS_IN_MINUTE",
    "MS_IN_HOUR",
    
    # Constants - Paths
    "LOGS_DIR",
    "CONFIG_DIR",
    "DATA_DIR",
    "TEMP_DIR",
    "WORKSPACE_DIR",
    
    # Constants - Defaults
    "DEFAULT_TIMEOUT",
    "DEFAULT_PAGE_SIZE",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_RETRY_DELAY",
    "DEFAULT_MAX_CONCURRENT_JOBS",
    "DEFAULT_OLLAMA_TIMEOUT",
    "DEFAULT_OLLAMA_MAX_CONCURRENCY",
    "DEFAULT_OLLAMA_CHAT_MODEL",
    "DEFAULT_OLLAMA_EMBED_MODEL",
    "DEFAULT_TELEGRAM_GLOBAL_MSG_PER_SEC",
    "DEFAULT_TELEGRAM_PER_CHAT_MSG_PER_SEC",
    "DEFAULT_MAX_TOOL_TURNS",
    "DEFAULT_AGENT_TIMEOUT",
    
    # Constants - Feature Flags
    "FEATURE_MEMORY_ENABLED",
    "FEATURE_SCHEDULER_ENABLED",
    "FEATURE_SUBAGENTS_ENABLED",
    "FEATURE_WEB_SEARCH_ENABLED",
    "FEATURE_CODE_EXECUTION_ENABLED",
    
    # Constants - Events
    "EVENT_APP_STARTUP",
    "EVENT_APP_SHUTDOWN",
    "EVENT_REQUEST_START",
    "EVENT_REQUEST_END",
    "EVENT_JOB_START",
    "EVENT_JOB_END",
    "EVENT_JOB_ERROR",
    "EVENT_MEMORY_CREATE",
    "EVENT_MEMORY_UPDATE",
    "EVENT_MEMORY_DELETE",
    "EVENT_TOOL_CALL",
    "EVENT_TOOL_ERROR",
    
    # Constants - Error Codes
    "ERROR_CODE_UNKNOWN",
    "ERROR_CODE_TIMEOUT",
    "ERROR_CODE_RATE_LIMIT",
    "ERROR_CODE_VALIDATION",
    "ERROR_CODE_NOT_FOUND",
    "ERROR_CODE_UNAUTHORIZED",
    "ERROR_CODE_FORBIDDEN",
    "ERROR_CODE_CONFLICT",
    "ERROR_CODE_INTERNAL",
    "ERROR_CODE_SERVICE_UNAVAILABLE",
]
