"""Canonical Memory v1.5 error codes."""

ERR_MEM_NOT_ELIGIBLE = "ERR_MEM_NOT_ELIGIBLE"
ERR_MEM_BLOCKED_CATEGORY = "ERR_MEM_BLOCKED_CATEGORY"
ERR_MEM_SECRET_DETECTED = "ERR_MEM_SECRET_DETECTED"
ERR_MEM_DUPLICATE = "ERR_MEM_DUPLICATE"
ERR_MEM_NOT_FOUND = "ERR_MEM_NOT_FOUND"
ERR_MEM_PAUSED = "ERR_MEM_PAUSED"
ERR_THREAD_NOT_FOUND = "ERR_THREAD_NOT_FOUND"
ERR_THREAD_REF_INVALID = "ERR_THREAD_REF_INVALID"

__all__ = [
    "ERR_MEM_NOT_ELIGIBLE",
    "ERR_MEM_BLOCKED_CATEGORY",
    "ERR_MEM_SECRET_DETECTED",
    "ERR_MEM_DUPLICATE",
    "ERR_MEM_NOT_FOUND",
    "ERR_MEM_PAUSED",
    "ERR_THREAD_NOT_FOUND",
    "ERR_THREAD_REF_INVALID",
]
